CREATE TABLE USERS_ROLES_HOOK_LOG
(
  USERID         NUMBER(30)                     NOT NULL,
  USERNAME       VARCHAR2(50 BYTE),
  ROLEID         NUMBER(30)                     NOT NULL,
  ROLENAME       VARCHAR2(50 BYTE),
  INSERT_USER    VARCHAR2(50 BYTE),
  INSERT_USERID  NUMBER(30)                     NOT NULL,
  INSERT_DATE    TIMESTAMP(6),
  ACTION         VARCHAR2(50 BYTE),
  INFO           VARCHAR2(50 BYTE)
);/
